// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// VolumeNodeAffinity defines constraints that limit what nodes this
    /// volume can be accessed from.
    /// </summary>
    public partial class Iok8sapicorev1VolumeNodeAffinity
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1VolumeNodeAffinity
        /// class.
        /// </summary>
        public Iok8sapicorev1VolumeNodeAffinity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1VolumeNodeAffinity
        /// class.
        /// </summary>
        /// <param name="required">Required specifies hard node constraints
        /// that must be met.</param>
        public Iok8sapicorev1VolumeNodeAffinity(Iok8sapicorev1NodeSelector required = default(Iok8sapicorev1NodeSelector))
        {
            Required = required;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets required specifies hard node constraints that must be
        /// met.
        /// </summary>
        [JsonProperty(PropertyName = "required")]
        public Iok8sapicorev1NodeSelector Required { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Required != null)
            {
                Required.Validate();
            }
        }
    }
}
