// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// NodeDaemonEndpoints lists ports opened by daemons running on the Node.
    /// </summary>
    public partial class Iok8sapicorev1NodeDaemonEndpoints
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1NodeDaemonEndpoints
        /// class.
        /// </summary>
        public Iok8sapicorev1NodeDaemonEndpoints()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1NodeDaemonEndpoints
        /// class.
        /// </summary>
        /// <param name="kubeletEndpoint">Endpoint on which Kubelet is
        /// listening.</param>
        public Iok8sapicorev1NodeDaemonEndpoints(Iok8sapicorev1DaemonEndpoint kubeletEndpoint = default(Iok8sapicorev1DaemonEndpoint))
        {
            KubeletEndpoint = kubeletEndpoint;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets endpoint on which Kubelet is listening.
        /// </summary>
        [JsonProperty(PropertyName = "kubeletEndpoint")]
        public Iok8sapicorev1DaemonEndpoint KubeletEndpoint { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (KubeletEndpoint != null)
            {
                KubeletEndpoint.Validate();
            }
        }
    }
}
