// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Handler defines a specific action that should be taken
    /// </summary>
    public partial class Iok8sapicorev1Handler
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1Handler class.
        /// </summary>
        public Iok8sapicorev1Handler()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1Handler class.
        /// </summary>
        /// <param name="exec">One and only one of the following should be
        /// specified. Exec specifies the action to take.</param>
        /// <param name="httpGet">HTTPGet specifies the http request to
        /// perform.</param>
        /// <param name="tcpSocket">TCPSocket specifies an action involving a
        /// TCP port. TCP hooks not yet supported</param>
        public Iok8sapicorev1Handler(Iok8sapicorev1ExecAction exec = default(Iok8sapicorev1ExecAction), Iok8sapicorev1HTTPGetAction httpGet = default(Iok8sapicorev1HTTPGetAction), Iok8sapicorev1TCPSocketAction tcpSocket = default(Iok8sapicorev1TCPSocketAction))
        {
            Exec = exec;
            HttpGet = httpGet;
            TcpSocket = tcpSocket;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets one and only one of the following should be specified.
        /// Exec specifies the action to take.
        /// </summary>
        [JsonProperty(PropertyName = "exec")]
        public Iok8sapicorev1ExecAction Exec { get; set; }

        /// <summary>
        /// Gets or sets hTTPGet specifies the http request to perform.
        /// </summary>
        [JsonProperty(PropertyName = "httpGet")]
        public Iok8sapicorev1HTTPGetAction HttpGet { get; set; }

        /// <summary>
        /// Gets or sets tCPSocket specifies an action involving a TCP port.
        /// TCP hooks not yet supported
        /// </summary>
        [JsonProperty(PropertyName = "tcpSocket")]
        public Iok8sapicorev1TCPSocketAction TcpSocket { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (HttpGet != null)
            {
                HttpGet.Validate();
            }
            if (TcpSocket != null)
            {
                TcpSocket.Validate();
            }
        }
    }
}
