// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// DaemonEndpoint contains information about a single Daemon endpoint.
    /// </summary>
    public partial class Iok8sapicorev1DaemonEndpoint
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1DaemonEndpoint
        /// class.
        /// </summary>
        public Iok8sapicorev1DaemonEndpoint()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1DaemonEndpoint
        /// class.
        /// </summary>
        /// <param name="port">Port number of the given endpoint.</param>
        public Iok8sapicorev1DaemonEndpoint(int port)
        {
            Port = port;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets port number of the given endpoint.
        /// </summary>
        [JsonProperty(PropertyName = "Port")]
        public int Port { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
