// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// VolumeError captures an error encountered during a volume operation.
    /// </summary>
    public partial class Iok8sapistoragev1beta1VolumeError
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapistoragev1beta1VolumeError
        /// class.
        /// </summary>
        public Iok8sapistoragev1beta1VolumeError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8sapistoragev1beta1VolumeError
        /// class.
        /// </summary>
        /// <param name="message">String detailing the error encountered during
        /// Attach or Detach operation. This string maybe logged, so it should
        /// not contain sensitive information.</param>
        /// <param name="time">Time the error was encountered.</param>
        public Iok8sapistoragev1beta1VolumeError(string message = default(string), System.DateTimeOffset? time = default(System.DateTimeOffset?))
        {
            Message = message;
            Time = time;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets string detailing the error encountered during Attach
        /// or Detach operation. This string maybe logged, so it should not
        /// contain sensitive information.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets time the error was encountered.
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public System.DateTimeOffset? Time { get; set; }

    }
}
