// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SecretReference represents a Secret Reference. It has enough
    /// information to retrieve secret in any namespace
    /// </summary>
    public partial class Iok8sapicorev1SecretReference
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1SecretReference
        /// class.
        /// </summary>
        public Iok8sapicorev1SecretReference()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1SecretReference
        /// class.
        /// </summary>
        /// <param name="name">Name is unique within a namespace to reference a
        /// secret resource.</param>
        /// <param name="namespaceProperty">Namespace defines the space within
        /// which the secret name must be unique.</param>
        public Iok8sapicorev1SecretReference(string name = default(string), string namespaceProperty = default(string))
        {
            Name = name;
            NamespaceProperty = namespaceProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets name is unique within a namespace to reference a
        /// secret resource.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets namespace defines the space within which the secret
        /// name must be unique.
        /// </summary>
        [JsonProperty(PropertyName = "namespace")]
        public string NamespaceProperty { get; set; }

    }
}
