// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kubeleans.KubernetesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Iok8sapiauthorizationv1SelfSubjectRulesReviewSpec
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiauthorizationv1SelfSubjectRulesReviewSpec class.
        /// </summary>
        public Iok8sapiauthorizationv1SelfSubjectRulesReviewSpec()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiauthorizationv1SelfSubjectRulesReviewSpec class.
        /// </summary>
        /// <param name="namespaceProperty">Namespace to evaluate rules for.
        /// Required.</param>
        public Iok8sapiauthorizationv1SelfSubjectRulesReviewSpec(string namespaceProperty = default(string))
        {
            NamespaceProperty = namespaceProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets namespace to evaluate rules for. Required.
        /// </summary>
        [JsonProperty(PropertyName = "namespace")]
        public string NamespaceProperty { get; set; }

    }
}
