apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition 
metadata: 
  name: grainfunctions.kubeleans.io 
spec: 
  group: kubeleans.io 
  version: v1 
  scope: Namespaced 
  names: 
    plural: grainfunctions 
    singular: grainfunction 
    kind: GrainFunction 
    shortNames: 
    - gf
